name: Fuzz Testing

on: [push, pull_request]

jobs:
  fuzz-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.22"

      - name: Install go-fuzz
        run: go get -u github.com/dvyukov/go-fuzz/go-fuzz

      - name: Run fuzz tests
        run: go-fuzz-build && go-fuzz -bin go-fuzz.zip
