name: Static Analysis

on: [push, pull_request]

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.22"

      - name: Install gosec
        run: go get -u github.com/securego/gosec/v2/cmd/gosec

      - name: Run gosec
        run: gosec ./...
